### PR TITLE
Support for 1.1

### LINKED ISSUE #17: 1.1 is :sad-panda:
In 1.1, rail signals have their collision boxes hardcoded and so can no longer be used for ramps. https://forums.factorio.com/82623

I think the way forward is to make a dummy "placer" item that then spawns the ramp (as a normal entity), like this mod does: https://github.com/Scarabytes/FactorioRealisticElectricTrains/blob/master/Realistic_Electric_Trains_0.4.5/prototypes/entities.lua. Or appeal on the forums for a reversion, but I doubt that would happen given the change was to fix a crash.

### PR DESCRIPTION
**Pull request by Xcelled**
Closes #17 .

### CODE REVIEW

**Comment by Xcelled** [comment]
This is now to a state where games can be loaded in 1.1 and trains will jump properly / various other errors are resolved.

Ramps have been changed so they're no longer rail signals, but constant combinators (lol). However, ramps are _placed_ by using a "placer" that _is_ a rail signal, which gets them properly aligned with the tracks. When a placer is built, we swap it for the real thing.

It was... interesting making this work with the older entities in the previous save. I had to do some wild stuff.

I also moved/rewrote bits of code so they could be reused, most notably in the ramp prototype generation and the magnet ramp range setting.

Anyway, this is now like 80% done. Functionally, it works, but a few more things need to be done:

1. Adjust the ramp sprites by have the offsets mentioned [here](https://github.com/Kiplacon/Renai-Transportation/pull/18/files#diff-6162a6a775f20348f9ae6030fc952fba3318f1a067596436561849bc3cbf1ac5R6-R9) * 32 pixels, this will make the placer images line up properly
2. Uncomment the shift lines for the ramp sprites to re-fix them from the offset changes
3. Hook into `on_player_configured_blueprint` to swap ramps for their placers in blueprints
4. Verify copy/paste works

**Comment by Kiplacon** [comment]
Wow that's a lot of stuff. It's gonna take me a while to read through and understand everything but you're pretty good so I'm confident it works like a champ 😎. I'll take a look through and try to finish that checklist

**Comment by Xcelled** [comment]
I'm happy to keep plugging away at the 3rd and 4th items. If you have the original graphics on you, it'll probably be easier for you to do item 1, though my backup plan was going to be using imagemagick to separate the sprites, adjust them, and stitch them back together. That said I haven't really worked with actual graphics in Factorio before, so you'll probably have a better handle on those.

(And, of course, testing to make sure nothing unexpected was broken)

**Comment by Kiplacon** [comment]
How can I add stuff to your branch? I fixed up the graphics and changed the ramp from a combinator to a simple-entity-with-owner so that the interface wouldn't open when clicking the magnet ramp to set range. By the way, the train ramps never actually worked with copy/paste and blueprints so I'm not sure how to implement that

**Comment by Xcelled** [comment]
Does a simple-entity-with-owner support the graphics required? From reading the docs it seemed like it only supported a single direction of graphics. If we need to keep it at a combinator, I can probably hack something up to keep the gui closed...

If you checked out my branch (`git checkout Xcelled/mk/1.1`) before making your changes, you should be able to send them up by doing `git push`.

**Comment by Kiplacon** [comment]
I changed it and it did work. Directional support for simple-entities was actually added in 1.1.0. it even has render_layer as a property so I changed it to render in the right layer

**Comment by Xcelled** [comment]
Fascinating. I must have been bit by the prototype definitions not being updated until a few days after release.

Also if copy/paste didn't work before 1.1, I'm happy to leave that as "to be implemented in the future, maybe" :joy:

**Pull request merged**
