### PR TITLE
Cleanup train animation code and add scaling to vertical jumps

### PR DESCRIPTION
**Pull request by Xcelled**
While looking into https://github.com/robot256/MultipleUnitTrainControl/issues/14, I found myself mired in the animation logic for trains. I was able to break the calculations out into discrete steps which can be reused and are also easier to follow. The net result is rendering logic now does approximately 1/3rd as many calculations as it used to.

Then, because I was already there, I added some code which subtly scales trains that are jumping north-south. This gives the impression the train is rising into the air, which I've found missing from those jumps. The east-west jumps have the rotating cars but there was nothing to distinguish a north-south jump from a train that was merely speeding up and slowing down.

Example effect, though horiibly compressed to fit in a gif:

stretch-smol

### CODE REVIEW

**Comment by Xcelled** [comment]
Shadows aren't scaled, but maybe they should be.

**Comment by Kiplacon** [comment]
Haha that scaling looks great 😁. Yeah my animation method is pretty jank but that's just what I came up with at the time, I didn't really have anything else to reference. The shadow scaling should be fine, it's mostly just to help see how high it was in the air since it doesn't tilt or anything going up and down. I'll try out your cleaned up animations when I get some time

**Comment by Xcelled** [comment]
To be honest, I"m not sure if my updated code works exactly like yours for the magnet ramp. Mine adjusts gravity so the midpoint of the jump is always constant. I'm not entirely sure what yours was doing. (I'm a software engineer, anything beyond basic math is beyond me :joy:)

The sprite rotating code I likewise didn't exactly figure out what it did, but I was able to deduplicate it.

The standard jump logic should be the same - I used the standard kinematics equations, and then calculated the new value for gravity by setting the old and new calculations equal to each other and solving for the new gravity. Or at least, the computer did when I asked it to! Then I played around with the number that came out and noticed it was pretty close to 9.8 m/s^2 with an integer scale factor , which I'm assuming was intentional on your part :P

**Comment by Xcelled** [comment]
Oh, I just realized the mag ramp code is a quadratic xD

I added a scaling factor to the original equation and it's working again.

**Comment by Xcelled** [comment]
Buoyed by my success with the mag ramp, I did some more polishing with the animation code:

- Train scaling happens in all directions (though I'm not sure if it works as well going left/right)
- The shadow now scales appropriately when jumping (in all directions)
- Shadow size and offset now more closely match the non-jump shadow
- Shadows spin in the vertical direction

In the end, it all came together rather nicely (I think, anyway!) and really adds to the jumping effect, though I'll probably remove the horizontal train scaling:

train-v-small

train-h-small

**Comment by Kiplacon** [comment]
Those shadows look super smooth, it really transitions well from the original ground carriage's shadow. I'm a visuals guy so I like it a lot 😀. But shouldn't the shadow get bigger instead of smaller as the train flies higher, like how in cartoons the shadow of a falling object gets smaller and darker as it falls? 

Scaling the train going left to right does look a little weird, maybe it's not necessary or the effect should be lessened. 

I only adjust the "gravity" on the magnet ramp to limit it's height because it feels like that's what the magnet should be doing, but on a regular ramp it's free to go as high as it wants based on speed. Whatever approach you did for calculating that movement is probably more mathematical than mine, I just put equations that looked like arcs into desmos online grapher and changed the numbers until I figured out which should be manipulated in the code to make the jump look right lol. Although for the left/right spinning it's a backwards n-shaped curve that first dips negative for the quick backwards tilt off the ramp, then gradually increases to a positive value for the slow forwards rotation through the jump, then quickly dips again to 0 for the quick snap back to level with the track. It could be a x^2 curve, but then you wouldn't get the slight liftoff and touchdown spins

**Comment by Xcelled** [comment]
:woman_facepalming: That's what I get for doing this at 4am lol. You're absolutely right.

Graphics are not my strong suit :joy: 

Our movement calculations should be the same basic principle in that case - quadratics. We just used different scale factors to get there. I'm happy to leave the rotation function as it is :P

**Comment by Kiplacon** [comment]
Is there a way I can merge the changes into a test branch so I can test some things before combining it fully?

**Comment by Xcelled** [comment]
You'll have to use git locally to do that.

Assuming you've cloned the repo, and are on your test branch, I'd do something like this:

```sh
git remote add Xcelled git@github.com:Xcelled/Renai-Transportation.git # Tell git to also look into my fork of your repo
git fetch Xcelled # Tells git to copy all of the github branches to your local repo
git checkout -b my-combined-branch # Make a new branch off of your currently check out one
git merge Xcelled/mk/animations # Merge my branch into your combined branch
```

Once you're done testing the combined branch, you can delete it with `git branch -D my-combined-branch`

That's off the top of my head and I haven't actually tested it, so let me know if there are issues.

**Pull request merged**
