### PR TITLE
Split up control.lua

### PR DESCRIPTION
**Pull request by Xcelled**
A non-bugfix this time :D

When working on this mod, I've found control.lua to be rather unwieldy because of its size. To make it more manageable, I copy/pasted most of the functions into their own lua files and require'd them in control.lua. I was also able to deduplicate all of the on_x_built event handlers into a single handler.

Splitting this file up not only makes it easier to edit, but it also opens the door for more cleanup in the future. For example, the functions could be split further into modules that handle only a train, or only an inserter, etc.

I've tested this as much as I can easily do (which is jumping trains, throwing inserters, bounce pads, and zip lines) but any additional verification you can do is :100:

### CODE REVIEW

**Comment by Kiplacon** [comment]
Huh I didn't know you could divide up the file like that. I use a notepad++ plugin that keeps a list of bookmarks as a sort of Table of Contents list which is how I navigate the huge file, but I can see the organizational benefit of this. Are there any performance effects doing it this way?

**Comment by Xcelled** [comment]
No, it's all reassembled at parse time, when the script is loaded by the game. If anything, there are performance benefits to doing it this way since the code is smaller and reused.

If you're interested, I can spend some free time over the next few weeks making further pull requests to improve the organization of the code.

**Comment by Xcelled** [comment]
Also, as a point of interest, I use VS Code with the lua and factorio plugins, which gets factorio-specific autocompletes as well as things like parse error detection and "navigate to definition"

**Comment by Kiplacon** [comment]
I don't know what that all means but I'm sure it's meant to be helpful lol, I'll check out VS code. Since it doesn't affect the mod's function like you say, then it's up to you if you want to spend the time reorganizing the file. Obviously I navigate it okay right now because I'm the one who made it the way it is, but I'm not against cleaning it up to look nicer especially if it would help other people like yourself

**Pull request merged**
