### PR TITLE
Support jumping trains with locos in the back

### PR DESCRIPTION
**Pull request by Xcelled**
I was playing with this mod and noticed that "pusher" trains (ie, those with locos in the back instead of the front) don't work properly when jumped. Upon landing, the lead car immediately freezes in place, causing the following stock to land on top of it and destroy both of them.

This is apparently because factorio doesn't allow trains to be given a speed unless there's a locomotive in the train somewhere. Since the train is disassembled when jumping and reassembled when landing, the speed can't be set until a loco lands. When the train is headed by a loco, this is fine, but when it's headed by other stock, the speed setting fails and the newly spawned car remains stationary.

I fixed this by creating a new entity, a ghost locomotive, that's essentially a frictionless, powerless, invisible shell. When the mod lands a train, it checks if the first stock is a locomotive. If it isn't, it spawns the ghost loco ahead of the just-landed stock. This causes the first stock to join into a train with the ghost loco, and the subsequent speed setting succeeds. When a real locomotive lands, we remove any ghost locos from the train.

There's a slight edge case in this solution, namely that if the real loco is destroyed (or is never there, see below), the ghost loco will stay at the head of the train forever, or at least until it's taken off another jump.

I feel like train speed not being settable without a locomotive is a bug in factorio itself. It's possible to make a train that's moving with no loco (get the train moving and then press `v` while in the loco or destroy it), so it seems odd that a mod couldn't do this.

I've also made a test save for jumping push trains: [jump test.zip](https://github.com/Kiplacon/Renai-Transportation/files/5405396/jump.test.zip)

### CODE REVIEW

**Comment by Kiplacon** [comment]
That's awesome, thank you for investigating and even making a fix for the issue 🙂. Carriages actually can be given a speed without a locomotive, but only if that non-locomotive carriage is in manual driving mode. A cargo wagon by itself for example could be in automatic mode and have a schedule, it just won't move or do anything since, like you mentioned, it doesn't have a locomotive. 

I had a problem with that same mechanic as well when the front half of a landing train would jump again before the whole train landed. Trains switch to manual mode whenever a carriage is added or removed, so I made it so landing carriages would trigger an update to its newly connected train back to automatic driving mode so it could continue on its way after a jump. But if the front locomotive took off before the back of that train landed, then the next carriage to land would update the train to automatic mode and freeze the whole thing since the front locomotive took off and wasn't a part of the train anymore. From what you described, you found an extra detail that a mid-takeoff/landing train will work so long as at least one locomotive is on the ground when the last carriage lands.

My fix to that interaction was to only have the first and last carriages of a train switch the train to automatic mode, and that last carriage only if the whole train was on the ground. But in this way, a train being pushed will crash when the first carriage lands. A possible alternate fix that's smaller code-wise would be to just add a condition that the first carriage landing has to be a locomotive for it to switch to automatic mode, that way it can still move forward in manual mode to make room for the next carriage and the last carriage can set it to automatic. The disadvantage there is that if there's a fork right after the landing point, the train will be in manual mode and take the default path, which might not be the right direction. Your fix would definitely make the train more functionally complete, I'll try both and see what I can find.

Thank you again Xcelled 😎

**Comment by Xcelled** [comment]
D'oh I can't believe I missed the manual mode thing...

**Comment by Kiplacon** [comment]
lol no worries, I has to mess around with the trains for hours before I figured that out. I don't think it's possible to get a lone cargo wagon into automatic mode without a locomotive through vanilla means anyway so it's not something readily apparent

**Comment by Xcelled** [comment]
I ran into more weirdness tangentially related to this: because automatic mode is only set when the first and last cars land, long trains can blow right past a fork they have to take, because they're in manual mode still. (the exact situation was a 1L-8W train that landed 6 car lengths before a fork).

My thinking was to change the guard around automatic mode to check for at least one locomotive driving forwards. This worked, more or less.

Unfortunately, I ran into a lot of unrelated problems with the speed, especially in the context of two closely placed jumps. These problems occurred without _any_ of my changes - I tested with a clean master branch.

The following two scenarios use 1 loco fueled with nuclear fuel, 6 artillery wagons. and two ramps ~2 car lengths apart. 

Taking a long train off closely placed jumps can cause the train carriages between the two to suddenly fly backwards. This seems to be caused by the orientation of the wagon coupled with the way the mod calculates if the speed for a train should be negative. Test case: When the wagons are "backwards" (their guns pointing towards the front of the loco), the wagons will suddenly completely reverse velocity when between the two ramps. Rotating the wagons so their guns are pointing towards the tail end of the train doesn't exhibit this issue. (it happens with all stock AFAICT, but artillery is the easiest to see the orientation)

However... that leads to the second problem. After going off the second ramp, the loco disconnects from the cars (which stop moving and die). I have no idea what causes this one, and I need to call it quits for tonight.

**Comment by Kiplacon** [comment]
Yeah it's quite the mess huh 😓. Chained ramp jumps have to have at least one carriage on the ground at all times for it to work properly, otherwise you get that sudden backwards fling.  If carriage 1 lands and jumps again before carriage 2 lands, then in that moment there are technically no real carriages on the ground and the whole thing loses reference point. I'm not really sure what the best solution is for now, it's probably the one with the fewest/least likely edge case issues. Train bounce pads are much better in that sense if you want two jumps super close together

**Pull request merged**
